markdown: rdiscount 
permalink: /:categories/:title 
title: Sealook' Blog
url: http://look618.com
subscribe: http://sealook.github.com/feed.xml
exclude: [ README.md, newpost.rb ]
domain: sealook.github.com
author: sealook
email: mrcnsdote@gmail.com
auto: true
twitterID: sealook
duoshuoShortname: sealook
navigation:
- text: Home
  url: / 
- text: Archive
  url: /archive/
- text: About
  url: /about/
- text: Links
  url: /links/
